language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO=https://www.djangoproject.com/download/1.5c2/tarball/
  - DJANGO=django==1.4.5 --use-mirrors

install:
  - pip install $DJANGO
  - pip install -r requirements/travis-ci.txt --use-mirrors

script: 
  - python runtests.py

notifications:
  email: false

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=django==1.4.5 --use-mirrors
    - python: "3.3"
      env: DJANGO=django==1.4.5 --use-mirrors
